# Generated by Django 3.1.4 on 2021-03-12 05:04

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_new',
        ),
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(default=datetime.datetime(2021, 3, 12, 5, 4, 25, 850076, tzinfo=utc), max_length=128, verbose_name='password'),
            preserve_default=False,
        ),
    ]
