"""
Django settings for ecom project.

Generated by 'django-admin startproject' using Django 3.1.4.

For more information on this file, see
https://docs.djangoproject.com/en/3.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.1/ref/settings/
"""

from ecom.settings.base import *
from ecom.settings.apps import *
from ecom.settings.app_vars import *
from ecom.settings.logger import *
from ecom.settings.database import *
from ecom.settings.third_party import *
from ecom.settings.celery import *
