"""
Django settings for hotel_booking project.

Generated by 'django-admin startproject' using Django 3.1.4.

For more information on this file, see
https://docs.djangoproject.com/en/3.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.1/ref/settings/
"""

from hotel_booking.settings.base import *
from hotel_booking.settings.apps import *
from hotel_booking.settings.app_vars import *
from hotel_booking.settings.logger import *
from hotel_booking.settings.database import *
from hotel_booking.settings.third_party import *
from hotel_booking.settings.celery import *
